apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-pod
  labels:
    app: accounting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting
  template:
    metadata:
      labels:
        app: accounting
    spec:
      containers:
        - name: accounting-container
          image: ebike3/accounting:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: SERVICE_ID
              value: "5"
            - name: DB_HOST
              value: accounting-postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: ebike3
            - name: DB_PASSWORD
              value: ebike3
            - name: DB_DATABASE
              value: accounting
            - name: KAFKA_BROKER
              value: kafka-service:9092
            - name: KAFKA_GROUP_ID
              value: accounting
---
apiVersion: v1
kind: Service
metadata:
  name: accounting-service
  labels:
    app: accounting
spec:
  selector:
    app: accounting
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
