apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stations-mongo-statefulset
  labels:
    app: stations
spec:
  serviceName: stations-mongo
  replicas: 1
  selector:
    matchLabels:
      app: stations
  template:
    metadata:
      labels:
        app: stations
    spec:
      containers:
        - name: stations-mongo-container
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: stations-mongo-service
  labels:
    app: stations
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: stations
